### ISSUE TITLE
relation to Secondary Certificate Authentication in HTTP/2 spec

### ISSUE THREAD

**Issue by bblfish** [w3c-ccg/http-signatures#10]
Hi, there is a very interesting spec evolving in the IETF, detailing nicely the problems to TLS client certificate use from HTTP/2.0, and providing what from a distance seems like a workable solution (I don't have the knowledge to evaluate it). It is located here:

https://datatracker.ietf.org/doc/draft-bishop-httpbis-http2-additional-certs/

This is much heavier than HTTP signatures, and would of course require full support by browser vendors to be used, etc... But it raises a few questions in my mind:

1. Given that the `additional-certs` spec is so much more involved and costly to implement, what are the benefits as compared to HTTP Signature ( what use cases does it address that HTTP-Signatures can't )? That would probably be something worth answering in the security review - even if indirectly since that spec is not a recommendation either, and hence cannot I think be cited.

2. Is there some way that the two proposals can interact nicely? Perhaps they are complementary?

**Comment by liamdennehy** [comment]
@bblfish It's been a long while since this issue was opened/updated, but no matter...

Please review https://github.com/w3c-dvcg/http-signatures/pull/48 that hopefully can give some clarity:

As far as I can tell, httpbis aims to add extra authentication information into the transport (extending Mutual TLS) so that e.g. a gateway can authenticate at one layer, then present a user's certificate/credentials inside that - all before any HTTP is exchanged. While that has some overlap with this specification (where ``Authorization`` and ``Signature`` headers can be used for authentication), this specification is more application-centric than the transport-centric httpbis. In that respect, they certainly can live alongside - TLS and httpbis are agnostic to application content (e.g. headers).

Additionally, the ``Signature`` header can turn a HTTP message into a digitally signed *document*, and even a non-repudiatable one at that. httpbis doesn't address this at all.

**Comment by liamdennehy** [comment]
@bblfish I'm closing this issue as it doesn't seem there is an overlap, we can reopen if you think there is something to discuss.
