### ISSUE TITLE
Questions related to `headers` interpretation

### ISSUE THREAD

**Issue by lukasz-szewc** [w3c-ccg/http-signatures#41]
Questions to following paragraph:

```
2.1.3.  headers

   OPTIONAL.  The `headers` parameter is used to specify the list of
   HTTP headers included when generating the signature for the message.
   If specified, it should be a lowercased, quoted list of HTTP header
   fields, separated by a single space character.  If not specified,
   implementations MUST operate as if the field were specified with a
   single value, the `Date` header, in the list of HTTP headers.  Note
   that the list order is important, and MUST be specified in the order
   the HTTP header field-value pairs are concatenated together during
   signing.
```

1. What if header is not lowercased? Is server obligated to reject such request? (the same question for more spaces as separator than one)
2. If there is obligation for all headers to be lowercased (when specified), why there is not similar obligation in case of not specified 'headers'. Why `Date` starts with capital letter?
3. How to treat `headers` when it is empty string? Is it invalid one or should `Date` be produced?

**Comment by liamdennehy** [comment]
1. The lowercase header name in the "headers" field is a convention. Constructing the signing string will lowercase the header names, so signers *should* provide lowercase names, but it is not required and will not affect the outcome.
2. `Date` here is the literal name of the header as appears in a HTTP/1.1 Request or Response, so is shown in proper as would normally be used in HTTP/1.1 messages.
3. An empty `headers` string means the signature is applied to an empty string (since no headers or (request-target) is included in the signing string) as the signer has explicitly stated "no headers", not "unspecified headers" which would invoke the `Date` default. The specification does not specify a minimum so technically this is a valid set, though this will be of little use.

Note that the convention to lowercase the header list is in anticipation of HTTP/2 being more prevalent. By convention (though not required), HTTP/1.1 specifies headers in Proper Case, while HTTP/2 headers are lowercased, so this is an attempt to be conformant with the new protocol. Additionally, encouraging them to be specified in lowercase reinforces that concept that any headers specified in a Request or Response in differing cases only are in fact the same header.

**Comment by liamdennehy** [comment]
@lukasz-szewc Please see the referenced Pull Request (#47) and see if it addresses your original questions properly.

**Comment by liamdennehy** [comment]
@lukasz-szewc PR #47 is merged, would you like to mark this issue resolved?

**Comment by lukasz-szewc** [comment]
@liamdennehy closed
